export const seedProducts = [
  {
    "id": "1",
    "name": "Avacado",
    "category": "Fruits",
    "price": 84,
    "unit": "kg",
    "stock": 31,
    "farmerName": "Local Farmer",
    "description": "Fresh avacado directly from the farm.",
    "imageUrl": "/Fruits/avacado.jpg",
    "createdAt": "2026-05-16T07:02:49.230Z"
  },
  {
    "id": "2",
    "name": "Banana",
    "category": "Fruits",
    "price": 51,
    "unit": "kg",
    "stock": 104,
    "farmerName": "Local Farmer",
    "description": "Fresh banana directly from the farm.",
    "imageUrl": "/Fruits/banana.jpg",
    "createdAt": "2026-05-16T07:02:49.231Z"
  },
  {
    "id": "3",
    "name": "Black Berrys",
    "category": "Fruits",
    "price": 91,
    "unit": "kg",
    "stock": 48,
    "farmerName": "Local Farmer",
    "description": "Fresh black berrys directly from the farm.",
    "imageUrl": "/Fruits/black%20berrys.jpg",
    "createdAt": "2026-05-16T07:02:49.231Z"
  },
  {
    "id": "4",
    "name": "Custard Apple",
    "category": "Fruits",
    "price": 61,
    "unit": "kg",
    "stock": 75,
    "farmerName": "Local Farmer",
    "description": "Fresh custard apple directly from the farm.",
    "imageUrl": "/Fruits/custard%20apple.jpg",
    "createdAt": "2026-05-16T07:02:49.231Z"
  },
  {
    "id": "5",
    "name": "Dragon Fruit",
    "category": "Fruits",
    "price": 22,
    "unit": "kg",
    "stock": 109,
    "farmerName": "Local Farmer",
    "description": "Fresh dragon fruit directly from the farm.",
    "imageUrl": "/Fruits/dragon%20fruit.jpg",
    "createdAt": "2026-05-16T07:02:49.231Z"
  },
  {
    "id": "6",
    "name": "Fresh Corn",
    "category": "Fruits",
    "price": 101,
    "unit": "kg",
    "stock": 45,
    "farmerName": "Local Farmer",
    "description": "Fresh fresh corn directly from the farm.",
    "imageUrl": "/Fruits/fresh%20corn.jpg",
    "createdAt": "2026-05-16T07:02:49.231Z"
  },
  {
    "id": "7",
    "name": "Goa",
    "category": "Fruits",
    "price": 115,
    "unit": "kg",
    "stock": 63,
    "farmerName": "Local Farmer",
    "description": "Fresh goa directly from the farm.",
    "imageUrl": "/Fruits/goa.jpg",
    "createdAt": "2026-05-16T07:02:49.231Z"
  },
  {
    "id": "8",
    "name": "Grapes",
    "category": "Fruits",
    "price": 113,
    "unit": "kg",
    "stock": 87,
    "farmerName": "Local Farmer",
    "description": "Fresh grapes directly from the farm.",
    "imageUrl": "/Fruits/grapes.jpg",
    "createdAt": "2026-05-16T07:02:49.231Z"
  },
  {
    "id": "9",
    "name": "Green Apples",
    "category": "Fruits",
    "price": 89,
    "unit": "kg",
    "stock": 50,
    "farmerName": "Local Farmer",
    "description": "Fresh green apples directly from the farm.",
    "imageUrl": "/Fruits/green%20apples.jpg",
    "createdAt": "2026-05-16T07:02:49.231Z"
  },
  {
    "id": "10",
    "name": "Green Grapes",
    "category": "Fruits",
    "price": 33,
    "unit": "kg",
    "stock": 74,
    "farmerName": "Local Farmer",
    "description": "Fresh green grapes directly from the farm.",
    "imageUrl": "/Fruits/green%20grapes.jpg",
    "createdAt": "2026-05-16T07:02:49.231Z"
  },
  {
    "id": "11",
    "name": "Jack Fruit",
    "category": "Fruits",
    "price": 34,
    "unit": "kg",
    "stock": 98,
    "farmerName": "Local Farmer",
    "description": "Fresh jack fruit directly from the farm.",
    "imageUrl": "/Fruits/jack%20fruit.jpg",
    "createdAt": "2026-05-16T07:02:49.231Z"
  },
  {
    "id": "12",
    "name": "Kiwi",
    "category": "Fruits",
    "price": 40,
    "unit": "kg",
    "stock": 49,
    "farmerName": "Local Farmer",
    "description": "Fresh kiwi directly from the farm.",
    "imageUrl": "/Fruits/kiwi.jpg",
    "createdAt": "2026-05-16T07:02:49.231Z"
  },
  {
    "id": "13",
    "name": "Lemon",
    "category": "Fruits",
    "price": 29,
    "unit": "kg",
    "stock": 30,
    "farmerName": "Local Farmer",
    "description": "Fresh lemon directly from the farm.",
    "imageUrl": "/Fruits/lemon.jpg",
    "createdAt": "2026-05-16T07:02:49.231Z"
  },
  {
    "id": "14",
    "name": "Mango",
    "category": "Fruits",
    "price": 33,
    "unit": "kg",
    "stock": 102,
    "farmerName": "Local Farmer",
    "description": "Fresh mango directly from the farm.",
    "imageUrl": "/Fruits/mango.jpg",
    "createdAt": "2026-05-16T07:02:49.231Z"
  },
  {
    "id": "15",
    "name": "Mulberry",
    "category": "Fruits",
    "price": 104,
    "unit": "kg",
    "stock": 56,
    "farmerName": "Local Farmer",
    "description": "Fresh mulberry directly from the farm.",
    "imageUrl": "/Fruits/mulberry.jpg",
    "createdAt": "2026-05-16T07:02:49.231Z"
  },
  {
    "id": "16",
    "name": "Muskmelon",
    "category": "Fruits",
    "price": 61,
    "unit": "kg",
    "stock": 16,
    "farmerName": "Local Farmer",
    "description": "Fresh muskmelon directly from the farm.",
    "imageUrl": "/Fruits/muskmelon.jpg",
    "createdAt": "2026-05-16T07:02:49.231Z"
  },
  {
    "id": "17",
    "name": "Oranges",
    "category": "Fruits",
    "price": 46,
    "unit": "kg",
    "stock": 27,
    "farmerName": "Local Farmer",
    "description": "Fresh oranges directly from the farm.",
    "imageUrl": "/Fruits/oranges.jpg",
    "createdAt": "2026-05-16T07:02:49.231Z"
  },
  {
    "id": "18",
    "name": "Papaya",
    "category": "Fruits",
    "price": 62,
    "unit": "kg",
    "stock": 43,
    "farmerName": "Local Farmer",
    "description": "Fresh papaya directly from the farm.",
    "imageUrl": "/Fruits/papaya.jpg",
    "createdAt": "2026-05-16T07:02:49.231Z"
  },
  {
    "id": "19",
    "name": "Pineapple",
    "category": "Fruits",
    "price": 66,
    "unit": "kg",
    "stock": 58,
    "farmerName": "Local Farmer",
    "description": "Fresh pineapple directly from the farm.",
    "imageUrl": "/Fruits/pineapple.jpg",
    "createdAt": "2026-05-16T07:02:49.231Z"
  },
  {
    "id": "20",
    "name": "Pomogranate",
    "category": "Fruits",
    "price": 35,
    "unit": "kg",
    "stock": 15,
    "farmerName": "Local Farmer",
    "description": "Fresh pomogranate directly from the farm.",
    "imageUrl": "/Fruits/pomogranate.jpg",
    "createdAt": "2026-05-16T07:02:49.231Z"
  },
  {
    "id": "21",
    "name": "Red Apples",
    "category": "Fruits",
    "price": 67,
    "unit": "kg",
    "stock": 34,
    "farmerName": "Local Farmer",
    "description": "Fresh red apples directly from the farm.",
    "imageUrl": "/Fruits/red%20apples.jpg",
    "createdAt": "2026-05-16T07:02:49.231Z"
  },
  {
    "id": "22",
    "name": "Sapota",
    "category": "Fruits",
    "price": 29,
    "unit": "kg",
    "stock": 46,
    "farmerName": "Local Farmer",
    "description": "Fresh sapota directly from the farm.",
    "imageUrl": "/Fruits/sapota.jpg",
    "createdAt": "2026-05-16T07:02:49.231Z"
  },
  {
    "id": "23",
    "name": "Start Fruits",
    "category": "Fruits",
    "price": 70,
    "unit": "kg",
    "stock": 105,
    "farmerName": "Local Farmer",
    "description": "Fresh start fruits directly from the farm.",
    "imageUrl": "/Fruits/start%20fruits.jpg",
    "createdAt": "2026-05-16T07:02:49.231Z"
  },
  {
    "id": "24",
    "name": "Strawberry",
    "category": "Fruits",
    "price": 97,
    "unit": "kg",
    "stock": 63,
    "farmerName": "Local Farmer",
    "description": "Fresh strawberry directly from the farm.",
    "imageUrl": "/Fruits/strawberry.jpg",
    "createdAt": "2026-05-16T07:02:49.231Z"
  },
  {
    "id": "25",
    "name": "Watermelon",
    "category": "Fruits",
    "price": 89,
    "unit": "kg",
    "stock": 89,
    "farmerName": "Local Farmer",
    "description": "Fresh watermelon directly from the farm.",
    "imageUrl": "/Fruits/watermelon.jpg",
    "createdAt": "2026-05-16T07:02:49.231Z"
  },
  {
    "id": "26",
    "name": "Bitter Gourd",
    "category": "Vegetables",
    "price": 70,
    "unit": "kg",
    "stock": 63,
    "farmerName": "Local Farmer",
    "description": "Fresh bitter gourd directly from the farm.",
    "imageUrl": "/Vegetables/bitter%20gourd.jpg",
    "createdAt": "2026-05-16T07:02:49.231Z"
  },
  {
    "id": "27",
    "name": "Brocli",
    "category": "Vegetables",
    "price": 67,
    "unit": "kg",
    "stock": 13,
    "farmerName": "Local Farmer",
    "description": "Fresh brocli directly from the farm.",
    "imageUrl": "/Vegetables/brocli.jpg",
    "createdAt": "2026-05-16T07:02:49.231Z"
  },
  {
    "id": "28",
    "name": "Cabbage",
    "category": "Vegetables",
    "price": 37,
    "unit": "kg",
    "stock": 50,
    "farmerName": "Local Farmer",
    "description": "Fresh cabbage directly from the farm.",
    "imageUrl": "/Vegetables/cabbage.jpg",
    "createdAt": "2026-05-16T07:02:49.231Z"
  },
  {
    "id": "29",
    "name": "Cali Flower",
    "category": "Vegetables",
    "price": 32,
    "unit": "kg",
    "stock": 53,
    "farmerName": "Local Farmer",
    "description": "Fresh cali flower directly from the farm.",
    "imageUrl": "/Vegetables/cali%20flower.webp",
    "createdAt": "2026-05-16T07:02:49.231Z"
  },
  {
    "id": "30",
    "name": "Capsicum",
    "category": "Vegetables",
    "price": 118,
    "unit": "kg",
    "stock": 99,
    "farmerName": "Local Farmer",
    "description": "Fresh capsicum directly from the farm.",
    "imageUrl": "/Vegetables/capsicum.jpg",
    "createdAt": "2026-05-16T07:02:49.231Z"
  },
  {
    "id": "31",
    "name": "Ivy Gourd.",
    "category": "Vegetables",
    "price": 70,
    "unit": "kg",
    "stock": 44,
    "farmerName": "Local Farmer",
    "description": "Fresh ivy gourd. directly from the farm.",
    "imageUrl": "/Vegetables/Ivy%20Gourd..jpg",
    "createdAt": "2026-05-16T07:02:49.231Z"
  },
  {
    "id": "32",
    "name": "Keera",
    "category": "Vegetables",
    "price": 66,
    "unit": "kg",
    "stock": 107,
    "farmerName": "Local Farmer",
    "description": "Fresh keera directly from the farm.",
    "imageUrl": "/Vegetables/keera.jpg",
    "createdAt": "2026-05-16T07:02:49.231Z"
  },
  {
    "id": "33",
    "name": "Ladies Finger",
    "category": "Vegetables",
    "price": 111,
    "unit": "kg",
    "stock": 106,
    "farmerName": "Local Farmer",
    "description": "Fresh ladies finger directly from the farm.",
    "imageUrl": "/Vegetables/ladies%20finger.webp",
    "createdAt": "2026-05-16T07:02:49.231Z"
  },
  {
    "id": "34",
    "name": "Onion",
    "category": "Vegetables",
    "price": 81,
    "unit": "kg",
    "stock": 74,
    "farmerName": "Local Farmer",
    "description": "Fresh onion directly from the farm.",
    "imageUrl": "/Vegetables/onion.jpg",
    "createdAt": "2026-05-16T07:02:49.231Z"
  },
  {
    "id": "35",
    "name": "Potato",
    "category": "Vegetables",
    "price": 90,
    "unit": "kg",
    "stock": 71,
    "farmerName": "Local Farmer",
    "description": "Fresh potato directly from the farm.",
    "imageUrl": "/Vegetables/potato.jpg",
    "createdAt": "2026-05-16T07:02:49.231Z"
  },
  {
    "id": "36",
    "name": "Tomatos",
    "category": "Vegetables",
    "price": 83,
    "unit": "kg",
    "stock": 10,
    "farmerName": "Local Farmer",
    "description": "Fresh tomatos directly from the farm.",
    "imageUrl": "/Vegetables/tomatos.jpg",
    "createdAt": "2026-05-16T07:02:49.231Z"
  },
  {
    "id": "37",
    "name": "Eggs",
    "category": "Dairy",
    "price": 96,
    "unit": "dozen",
    "stock": 65,
    "farmerName": "Local Farmer",
    "description": "Fresh eggs directly from the farm.",
    "imageUrl": "/dairy%20products/eggs.jpg",
    "createdAt": "2026-05-16T07:02:49.231Z"
  },
  {
    "id": "38",
    "name": "Milk Packets",
    "category": "Dairy",
    "price": 53,
    "unit": "litre",
    "stock": 89,
    "farmerName": "Local Farmer",
    "description": "Fresh milk packets directly from the farm.",
    "imageUrl": "/dairy%20products/milk%20packets.jpg",
    "createdAt": "2026-05-16T07:02:49.231Z"
  },
  {
    "id": "39",
    "name": "Natural Ghee",
    "category": "Dairy",
    "price": 44,
    "unit": "kg",
    "stock": 54,
    "farmerName": "Local Farmer",
    "description": "Fresh natural ghee directly from the farm.",
    "imageUrl": "/dairy%20products/natural%20ghee.jpg",
    "createdAt": "2026-05-16T07:02:49.231Z"
  },
  {
    "id": "40",
    "name": "Panner",
    "category": "Dairy",
    "price": 32,
    "unit": "kg",
    "stock": 74,
    "farmerName": "Local Farmer",
    "description": "Fresh panner directly from the farm.",
    "imageUrl": "/dairy%20products/panner.jpg",
    "createdAt": "2026-05-16T07:02:49.231Z"
  },
  {
    "id": "41",
    "name": "Bachalikura",
    "category": "Vegetables",
    "price": 105,
    "unit": "kg",
    "stock": 68,
    "farmerName": "Local Farmer",
    "description": "Fresh bachalikura directly from the farm.",
    "imageUrl": "/leafy%20vegetables/bachalikura.jpg",
    "createdAt": "2026-05-16T07:02:49.232Z"
  },
  {
    "id": "42",
    "name": "Chukka Kura",
    "category": "Vegetables",
    "price": 46,
    "unit": "kg",
    "stock": 87,
    "farmerName": "Local Farmer",
    "description": "Fresh chukka kura directly from the farm.",
    "imageUrl": "/leafy%20vegetables/chukka%20kura.jpg",
    "createdAt": "2026-05-16T07:02:49.232Z"
  },
  {
    "id": "43",
    "name": "Gongura",
    "category": "Vegetables",
    "price": 97,
    "unit": "kg",
    "stock": 19,
    "farmerName": "Local Farmer",
    "description": "Fresh gongura directly from the farm.",
    "imageUrl": "/leafy%20vegetables/gongura.jpg",
    "createdAt": "2026-05-16T07:02:49.232Z"
  },
  {
    "id": "44",
    "name": "Kale",
    "category": "Vegetables",
    "price": 41,
    "unit": "kg",
    "stock": 52,
    "farmerName": "Local Farmer",
    "description": "Fresh kale directly from the farm.",
    "imageUrl": "/leafy%20vegetables/kale.jpg",
    "createdAt": "2026-05-16T07:02:49.232Z"
  },
  {
    "id": "45",
    "name": "Menthikura",
    "category": "Vegetables",
    "price": 77,
    "unit": "kg",
    "stock": 67,
    "farmerName": "Local Farmer",
    "description": "Fresh menthikura directly from the farm.",
    "imageUrl": "/leafy%20vegetables/menthikura.jpg",
    "createdAt": "2026-05-16T07:02:49.232Z"
  },
  {
    "id": "46",
    "name": "Thotakura",
    "category": "Vegetables",
    "price": 26,
    "unit": "kg",
    "stock": 36,
    "farmerName": "Local Farmer",
    "description": "Fresh thotakura directly from the farm.",
    "imageUrl": "/leafy%20vegetables/thotakura.jpg",
    "createdAt": "2026-05-16T07:02:49.232Z"
  },
  {
    "id": "47",
    "name": "Brown Rice",
    "category": "Grains",
    "price": 75,
    "unit": "kg",
    "stock": 28,
    "farmerName": "Local Farmer",
    "description": "Fresh brown rice directly from the farm.",
    "imageUrl": "/Grains/brown%20rice.jpg",
    "createdAt": "2026-05-16T07:02:49.232Z"
  },
  {
    "id": "48",
    "name": "Wheat",
    "category": "Grains",
    "price": 99,
    "unit": "kg",
    "stock": 37,
    "farmerName": "Local Farmer",
    "description": "Fresh wheat directly from the farm.",
    "imageUrl": "/Grains/wheat.jpg",
    "createdAt": "2026-05-16T07:02:49.232Z"
  },
  {
    "id": "49",
    "name": "White Rice",
    "category": "Grains",
    "price": 23,
    "unit": "kg",
    "stock": 107,
    "farmerName": "Local Farmer",
    "description": "Fresh white rice directly from the farm.",
    "imageUrl": "/Grains/White%20rice.jpg",
    "createdAt": "2026-05-16T07:02:49.232Z"
  },
  // ---- Spices ----
  {
    "id": "101",
    "name": "Cumin",
    "category": "Spices",
    "price": 120,
    "unit": "kg",
    "stock": 200,
    "farmerName": "Local Farmer",
    "description": "Premium quality cumin seeds.",
    "imageUrl": "/spi/cumin.jpg",
    "createdAt": "2026-05-16T07:02:49.232Z"
  },
  {
    "id": "102",
    "name": "Turmeric",
    "category": "Spices",
    "price": 110,
    "unit": "kg",
    "stock": 180,
    "farmerName": "Local Farmer",
    "description": "Fresh turmeric powder.",
    "imageUrl": "/spi/turmeric.jpg",
    "createdAt": "2026-05-16T07:02:49.232Z"
  },
  {
    "id": "103",
    "name": "Coriander",
    "category": "Spices",
    "price": 115,
    "unit": "kg",
    "stock": 190,
    "farmerName": "Local Farmer",
    "description": "Fragrant coriander seeds.",
    "imageUrl": "/spi/coriander.jpg",
    "createdAt": "2026-05-16T07:02:49.232Z"
  },
  {
    "id": "104",
    "name": "Black Pepper",
    "category": "Spices",
    "price": 130,
    "unit": "kg",
    "stock": 150,
    "farmerName": "Local Farmer",
    "description": "Whole black peppercorns.",
    "imageUrl": "/spi/black pepper.jpg",
    "createdAt": "2026-05-16T07:02:49.232Z"
  },
  {
    "id": "105",
    "name": "Cardamom",
    "category": "Spices",
    "price": 140,
    "unit": "kg",
    "stock": 120,
    "farmerName": "Local Farmer",
    "description": "Green cardamom pods.",
    "imageUrl": "/spi/cardamom.jpg",
    "createdAt": "2026-05-16T07:02:49.232Z"
  }
];
